### ISSUE TITLE
Add 'back compatibility' imports to spark package

### ISSUE THREAD

**Issue by centralniak** [zero323/pyspark-stubs#128]
As of `v2.4.0`, pyspark has some 'back compatibility' imports in the `spark` package that are missing in the stub:
https://github.com/apache/spark/blob/v2.4.0/python/pyspark/__init__.py#L114 

Can we add them?

**Comment by zero323** [comment]
As long as it doesn't break anything (stubs often require additional imports, and it's not hard to get awkward circular dependency) I don't see any problem with that. Could you create a PR @centralniak?

**Comment by centralniak** [comment]
I'll try to create one next week.
