### ISSUE TITLE
pylint vscode?

### ISSUE THREAD

**Issue by AlJohri** [zero323/pyspark-stubs#172]
does this help with pylint warnings on vscode by any chance? I tried it out and the warnings kept appearing, wasn't sure if I was using it wrong.

for now I followed the advice in this SO answer: https://stackoverflow.com/a/52119469/1667241

```
"python.linting.pylintArgs": [
        "--generated-members=pyspark.*",
        "--extension-pkg-whitelist=pyspark",
        "--ignored-modules=pyspark.sql.functions"
    ]
```

was hoping there was a better solution. thanks!

**Comment by zero323** [comment]
@AlJohri Pylint doesn't support type annotations yet (PyCQA/pylint#647), so my educated guess is that it won't have any impact on your Visual Studio Code environment.

That being said, in my experience Mypy is at least as efficient in detecting coding mistakes, if not better. So you might consider re-configuring your environment (https://code.visualstudio.com/docs/python/linting#_specific-linters), possibly leaving style mistakes Pylint (or Flake8).
