### ISSUE TITLE
hint of lit, col in pyspark.sql.functions

### ISSUE THREAD

**Issue by rfouyang** [zero323/pyspark-stubs#179]
Is it possible to add the hint for lit, col in pyspark.sql.functions

**Comment by zero323** [comment]
These annotations already exist @rfouyang. `col`

https://github.com/zero323/pyspark-stubs/blob/8a3b45127f9834d361c6fbb783cde17d361316ac/third_party/3/pyspark/sql/functions.pyi#L173

and `lit`

https://github.com/zero323/pyspark-stubs/blob/8a3b45127f9834d361c6fbb783cde17d361316ac/third_party/3/pyspark/sql/functions.pyi#L191

**Comment by zero323** [comment]
If you experience any problems with these it might be, because your environment doesn't use type annotations. See for example #172 in VSCode.
