### ISSUE TITLE
DataFrame.distinct is not supported in 2.4.0.postX

### ISSUE THREAD

**Issue by chehsunliu** [zero323/pyspark-stubs#227]
It seems this function has existed since 1.3:
https://github.com/apache/spark/blob/1b99d0cca4b4fb6d193091f92c46c916b70cd84e/python/pyspark/sql/dataframe.py#L776-L783

**Comment by zero323** [comment]
Issue introduced by accident with cebd8d28cc6dfa6e5de37c3d87e3d048338f36b0, fixed on master by 623b0c0330ef4c276b0c80e586ec4cb7700557d8

**Comment by zero323** [comment]
Resolved by 49bb82ff4f488e50ce829422d104e8dbe683194f on 2.4 and 1bc62b01da4aa53a843571cb140adf734cd4231f on 2.3.
