### ISSUE TITLE
Comparisons with date values unsupported 

### ISSUE THREAD

**Issue by mark-oppenheim** [zero323/pyspark-stubs#273]
Using *2.4.0.post6*

```from datetime import date
sf.lit(date.today()) < date.today()
```

mypy reports  ```Unsupported operand types for < ("Column" and "date")```

I suspect the solution is as simple as changing the definitions of lt, gt, lte, gte etc in master/third_party/3/pyspark/sql/column.pyi from `Union[Column, LiteralType, DecimalLiteral])` to `Union[Column, LiteralType, DecimalLiteral, DateTimeLiteral])` `DateTimeLiteral` is already imported but appears not to be used.

**Comment by zero323** [comment]
Thank you for reporting @mark-oppenheim.

**Comment by zero323** [comment]
Resolved by #274

**Comment by mark-oppenheim-edf** [comment]
That's an amazing turn-around time.  Thanks!
