### ISSUE TITLE
Java <-> Python conversion in `pyspark.mllib.common` missing

### ISSUE THREAD

**Issue by qudade** [zero323/pyspark-stubs#388]
The functions `_py2java` and `_java2py` in `pyspark.mllib.common` are used to transfer objects between the pyspark and the spark side of things.

For some advanced use cases they are required, hence it makes sense to add them to the stubs.

This applies to 2.4.x, too.

**Comment by zero323** [comment]
Closing as per [comment](https://github.com/zero323/pyspark-stubs/pull/389#issuecomment-609088891).
