### ISSUE TITLE
Option Values are Optional

### ISSUE THREAD

**Issue by qudade** [zero323/pyspark-stubs#390]
When setting the options for `DataFrameReader`, `DataFrameWriter` or `DataStreamReader` then `None` is an allowed value.

[DFReader](https://github.com/apache/spark/blob/d2ff5c5bfb29a7b22df3cb49b6584c3e2bec397c/python/pyspark/sql/readwriter.py#L124), [DFWriter](https://github.com/apache/spark/blob/d2ff5c5bfb29a7b22df3cb49b6584c3e2bec397c/python/pyspark/sql/readwriter.py#L699) and [DSReader](https://github.com/apache/spark/blob/d2ff5c5bfb29a7b22df3cb49b6584c3e2bec397c/python/pyspark/sql/streaming.py#L359) are using [`pyspark.sql.utils.to_str()§](https://github.com/apache/spark/blob/a4fc6a6e98fcd7ea5ec7a006864ade855c4b5a59/python/pyspark/sql/utils.py#L181)

**Comment by zero323** [comment]
In general looks acceptable, nonetheless I have to ask - what application do you find for `None` here? If I recall correctly correctly all built-in options just ignore `null`.

**Comment by qudade** [comment]
yes, this is true.

In our code we have convenience functions that allow to overwrite default values - if the user is not specifying some parameter the value is `None` and setting the option is a noop. Since `DataFrameReader/Writer` have fluent APIs it would be much more verbose to first check if a parameter has been set or not. (i.e. `...write().option("a", val1).option("b", val2)...`).

**Comment by zero323** [comment]
OK. Makes sense. Thanks.
