### ISSUE TITLE
boolean for `filter` and `where`

### ISSUE THREAD

**Issue by qudade** [zero323/pyspark-stubs#392]
Having a dataframe `df` we can do `df.filter(F.col(a) == b)`. Technically this condition is a `Column` (because `DataFrame.__eq__ -> Column`. mypy however here sees a bool and complains about incompatible types.

Applies to 2.4, too.

**Comment by zero323** [comment]
As per this comment https://github.com/zero323/pyspark-stubs/pull/393#pullrequestreview-387518042 changing signature this way is not acceptable.

**Comment by qudade** [comment]
@zero323 I understand that you don't accept my fix - but the problem described in this issue in unsolved.

To use something like `...where(F.col("a") == b)` is very common - to mark all these occurrences with `type: ignore` would look really strange.

I hope that something like you suggested in [your comment](https://github.com/zero323/pyspark-stubs/pull/393#pullrequestreview-387518042) could help to solve this issue.

For us, this is a blocking issue to integrate the pyspark stubs into our production code.

**Comment by qudade** [comment]
@zero323 I still think that the bug is a problem. Discarding #393 is correct as you explained but that doesn't solve this problem.
