### ISSUE TITLE
How to properly annotate pandas_udf functions?

### ISSUE THREAD

**Issue by harpaj** [zero323/pyspark-stubs#422]
## Describe the bug
Hello! This is (probably) not a bug, just a question.
I tried to upgrade from an older version of the stubs to the current one.
This was breaking the annotations for the pandas UDFs, and I don't understand from a first look at the code what I am doing wrong/how I should design the annotation instead.

## To Reproduce

- Minimal code snippet

    ```python
    def _lowercase_text_pd(series: "Series") -> "Series":
        return series.str.lower()

    lowercase_text = F.pandas_udf(_lowercase_text_pd, T.StringType())
    ```

- MyPy command
```bash
error: No overload variant of "pandas_udf" matches argument types "Callable[[Any], Any]", "StringType"
note: Possible overload variants:
note:     def pandas_udf(f: Union[Union[AtomicType, str], ArrayType], returnType: Literal[200]) -> Callable[[<union: 11 items>], UserDefinedFunctionLike]
note:     def pandas_udf(f: Union[StructType, str], returnType: Literal[201]) -> Callable[[Union[Callable[[Any], Any], Callable[[Any, Any], Any]]], GroupedMapPandasUserDefinedFunction]
note:     def pandas_udf(f: Union[Union[AtomicType, str], ArrayType], returnType: Literal[202]) -> Callable[[<union: 11 items>], UserDefinedFunctionLike]
note:     <9 more non-matching overloads not shown>
```

## Environment
- pyspark-stubs version and commit hash (if applicable): 2.4.0.post8
- MyPy version: 2.4.0.post8
- Python version: 3.7.7
- PySpark version: 2.4.6

**Comment by zero323** [comment]
Hi. If I recall correctly, in case of `eval_type` is mandatory.

**Comment by zero323** [comment]
I am closing this @harpaj, but feel free to ask if you have any follow-up questions.
