### ISSUE TITLE
OneHotEncoder has invalid type for inputCol param

### ISSUE THREAD

**Issue by Genarito** [zero323/pyspark-stubs#453]
## Describe the bug
Given the example:

```python
OneHotEncoder(inputCol=['test'], outputCol='test_new')
```

You'll receive the following error:

> TypeError: Invalid param value given for param "inputCol". Could not convert <class 'list'> to string type

But in the corresponding stub file the param type is defined as `Optional[List[str]] = ...,`. I think It should be `inputCol: Optional[str] = ...,`, even the name of the param `inputCol` indicates a single value.

## Environment
- Python version: 3.6.8 
- PySpark version: 2.4.3

**Comment by zero323** [comment]
Thanks for reporting. I see the source of the problem in 3.0 / 3.1, but not 2.4. Could you provide the version of stubs you use?

**Comment by Genarito** [comment]
Sorry! I'm using the `3.0.0` version of stubs
