### ISSUE TITLE
Support string type in pyspark.sql.DataFrameReader.csv's schema parameter

### ISSUE THREAD

**Issue by chehsunliu** [zero323/pyspark-stubs#507]
## Describe the bug

The [official document](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrameReader.csv) says that:
> **schema** - an optional `pyspark.sql.types.StructType` for the input schema or **a DDL-formatted string** (For example `col0 INT, col1 DOUBLE`).

but now:

```
qq.py:4: error: Argument "schema" to "csv" of "DataFrameReader" has incompatible type "str"; expected "Optional[StructType]"
Found 1 error in 1 file (checked 1 source file)
```

## To Reproduce

- Minimal code snippet

    ```python
    from pyspark.sql import SparkSession
    
    spark = SparkSession.builder.appName("abc").getOrCreate()
    spark.read.csv("/tmp/abc", schema="col0 INT, col1 STRING")
    ```

- MyPy command

    ```bash
    mypy --config-file mypy.ini ./qq.py
    ```

- MyPy config

    ```ini
    [mypy]
    check_untyped_defs = True
    disallow_any_generics = True
    disallow_incomplete_defs = True
    disallow_subclassing_any = True
    disallow_untyped_calls = True
    disallow_untyped_defs = True
    ignore_missing_imports = True
    no_implicit_optional = True
    no_implicit_reexport = True
    strict_equality = True
    warn_redundant_casts = True
    warn_unused_configs = True
    warn_unused_ignores = True
    ```

## Expected behavior

Report no error when `schema` is `str`.

## Environment

- pyspark-stubs version: 2.4.0.post8
- MyPy version: 0.740
- Python version: 3.6.9
- PySpark version: 2.4.3

**Comment by zero323** [comment]
Thanks for reporting @chehsunliu 

__Note__

This should be also applied to `json`.
