### ISSUE TITLE
Allow latest version of pyspark

### ISSUE THREAD

**Issue by jruales** [zero323/pyspark-stubs#557]
Currently, pyspark-stubs is limiting pyspark to have version
`pyspark>=3.0.0.dev0,<3.1.0`

However, we would like to install the latest version of pyspark (3.2.1) which has addressed the Log4J vulnerability.

Could pyspark-stubs please change the required pyspark version to allow the latest one?

**Comment by jruales** [comment]
Oh, I just saw in the README that now stubs are part of the main pyspark project
![image](https://user-images.githubusercontent.com/1588988/160189693-9cb58b33-acc7-4a1b-b260-d80cd851db7b.png)

**Comment by zero323** [comment]
Yeah, the project has been merged with main Spark repository :)
